---
# We just wrap `build` so this is really it
name: "jellyfin-ffmpeg"
version: "4.4.1-3"
packages:
  - buster-amd64
  - buster-armhf
  - buster-arm64
  - bullseye-amd64
  - bullseye-armhf
  - bullseye-arm64
  - xenial-amd64
  - bionic-amd64
  - bionic-armhf
  - bionic-arm64
  - focal-amd64
  - focal-armhf
  - focal-arm64
  - hirsute-amd64
  - hirsute-armhf
  - hirsute-arm64
  - impish-amd64
  - impish-armhf
  - impish-arm64
