on:
  workflow_call:
    inputs:
      os:
        required: true
        default: 'linux'
        type: string
      architectures:
        description: 'Stringified JSON object listing target architectures'
        required: true
        default: '["amd64"]'
        type: string
      release:
        required: false
        default: false
        type: boolean
    secrets:
      deploy-host:
        required: false
      deploy-user:
        required: false
      deploy-key:
        required: false

jobs:
  build:
    name: 'Build Portable FFmpeg'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: ${{fromJson(inputs.architectures)}}
  
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Build Portable
        run: ./build-${{ inputs.os }}-${{ matrix.arch }} ./dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ inputs.os }}-${{ matrix.arch }}-portable
          path: dist

  publish:
    name: Publish Portable Release
    if: ${{ inputs.release }}
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: true
      matrix:
        arch: ${{fromJson(inputs.architectures)}}

    steps:
      - name: Set Versions
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)

      - name: Download Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ inputs.os }}-${{ matrix.arch }}-portable
          path: artifact

      - name: Prepare Release Assets
        run: |-
          pushd artifact
          find * -type f \( -name "*.xz" -o -name "*.zip" \) | while read file; do
            sha256sum "${file}" | tee "${file}.sha256sum"
          done
          popd

      - name: Upload GH Release Assets
        uses: shogo82148/actions-upload-release-asset@7eaf21378a56987478e34936683ba93ffb6c4f3c # v1.6.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          overwrite: true
          asset_path: |
            ./artifact/**/*.zip
            ./artifact/**/*.tar.xz
            ./artifact/**/*.sha256sum

      - name: Make Sure FFmpeg Directory Exists
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6 # v0.1.10
        with:
          host: ${{ secrets.deploy-host }}
          username: ${{ secrets.deploy-user }}
          key: ${{ secrets.deploy-key }}
          script_stop: true
          script: |-
            mkdir -p /srv/repository/releases/ffmpeg/${{ steps.set_version.outputs.no-v }}/

      - name: Upload Release Assets
        uses: burnett01/rsync-deployments@b247bfd3aff7245a6df1b3a64798f4176ca2a4a1 # 5.2.2
        with:
          switches: -vrptz
          path: ./artifact/*
          remote_path: /srv/repository/releases/ffmpeg/${{ steps.set_version.outputs.no-v }}/
          remote_host: ${{ secrets.deploy-host }}
          remote_user: ${{ secrets.deploy-user }}
          remote_key: ${{ secrets.deploy-key }}
