name: '🏗️ Build jellyfin-ffmpeg'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - jellyfin
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - jellyfin
    paths-ignore:
      - '**/*.md'

jobs:
  build_debian:
    uses: jellyfin/jellyfin-ffmpeg/.github/workflows/_meta.yaml@jellyfin
    with:
      distro: 'debian'
      codenames: '["buster", "bullseye"]'
      architectures: '["amd64", "arm64", "armhf"]'
      release: false

  build_ubuntu:
    uses: jellyfin/jellyfin-ffmpeg/.github/workflows/_meta.yaml@jellyfin
    with:
      distro: 'ubuntu'
      codenames: '["focal", "bionic", "impish", "hirsute"]'
      architectures: '["amd64", "arm64", "armhf"]'
      release: false

  build_windows:
    uses: jellyfin/jellyfin-ffmpeg/.github/workflows/_meta.yaml@jellyfin
    with:
      distro: 'windows'
      codenames: '["windows"]'
      architectures: '["win64"]'
      release: false
